name: clang-tidy

on:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Clang-Tidy
        run: |
          sudo apt-get -yqq update
          sudo apt-get -yqq install clang-tidy libomp-dev

      - name: Generate compile_commands.json
        run: |
          cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          # cmake --build build

      - name: Analyze
        run: |
          mkdir /tmp/clang-tidy-result
          clang-tidy -p build/ -export-fixes /tmp/clang-tidy-result/fixes.yaml src/* || true
          echo "${{ github.event.number }}" > /tmp/clang-tidy-result/pr-id.txt
          echo "${{ github.event.pull_request.head.repo.full_name }}" > /tmp/clang-tidy-result/pr-head-repo.txt
          echo "${{ github.event.pull_request.head.ref }}" > /tmp/clang-tidy-result/pr-head-ref.txt
        shell: bash

      - name: Check if the fixes.yaml file exists
        id: check-fixes-yaml-existence
        uses: autowarefoundation/autoware-github-actions/check-file-existence@v1
        with:
          files: /tmp/clang-tidy-result/fixes.yaml

      - name: Upload artifacts
        if: ${{ steps.check-fixes-yaml-existence.outputs.exists == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: clang-tidy-result
          path: /tmp/clang-tidy-result/

      - name: Mark the workflow as failed if the fixes.yaml file exists
        if: ${{ steps.check-fixes-yaml-existence.outputs.exists == 'true' }}
        run: |
          exit 1
        shell: bash
